# This is a basic workflow to help you get started with Actions
name: H
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
  schedule:
    # UTC (国内 UTC+8)
    - cron: '0 */3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  H:
    runs-on: ubuntu-22.04
    # 超时设置
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup FFmpeg using versions
        uses: Iamshankhadeep/setup-ffmpeg@v1.2
      - name: 'Environment Settings'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: 'Renew'
        env:
          URL_BASE: ${{ secrets.URL_BASE_H }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BARK_TOKEN: ${{ secrets.BARK_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: |  
          xvfb-run python3 ./main.py
          
          
      - name: 'Renew 2'
        env:
          URL_BASE: ${{ secrets.URL_BASE_H }}
          USERNAME: ${{ secrets.USERNAME_H_US }}
          PASSWORD: ${{ secrets.PASSWORD_H_US }}
          BARK_TOKEN: ${{ secrets.BARK_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: |  
          xvfb-run python3 ./main.py
          
          
      - name: 'Renew 3'
        env:
          URL_BASE: ${{ secrets.URL_BASE_H }}
          USERNAME: ${{ secrets.USERNAME_H_US2 }}
          PASSWORD: ${{ secrets.PASSWORD_H_US2 }}
          BARK_TOKEN: ${{ secrets.BARK_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: |  
          xvfb-run python3 ./main.py
